// Static list of NSE ticker symbols used for trade entry autocomplete.
// Source: NSE India — Nifty 50 constituents + popular mid/small-cap additions.
// In production, this would be replaced with a live NSE API call or a scheduled sync.

export const NSE_SYMBOLS = [
  // ── Nifty 50 ──────────────────────────────────────────────────────────────
  "ADANIPORTS",
  "APOLLOHOSP",
  "ASIANPAINT",
  "AXISBANK",
  "BAJAJ-AUTO",
  "BAJAJFINSV",
  "BAJFINANCE",
  "BHARTIARTL",
  "BPCL",
  "BRITANNIA",
  "CIPLA",
  "COALINDIA",
  "DIVISLAB",
  "DRREDDY",
  "EICHERMOT",
  "GRASIM",
  "HCLTECH",
  "HDFCBANK",
  "HDFCLIFE",
  "HEROMOTOCO",
  "HINDALCO",
  "HINDUNILVR",
  "ICICIBANK",
  "INDUSINDBK",
  "INFY",
  "ITC",
  "JSWSTEEL",
  "KOTAKBANK",
  "LT",
  "LTIM",
  "M&M",
  "MARUTI",
  "NESTLEIND",
  "NTPC",
  "ONGC",
  "POWERGRID",
  "RELIANCE",
  "SBILIFE",
  "SBIN",
  "SHREECEM",
  "SUNPHARMA",
  "TATACONSUM",
  "TATAMOTORS",
  "TATASTEEL",
  "TCS",
  "TECHM",
  "TITAN",
  "ULTRACEMCO",
  "WIPRO",
  // ── Popular additions ──────────────────────────────────────────────────────
  "ADANIENT",
  "ADANIGREEN",
  "ADANIPOWER",
  "AMBUJACEM",
  "AUROPHARMA",
  "BANKBARODA",
  "BERGEPAINT",
  "CANBK",
  "CHOLAFIN",
  "COLPAL",
  "DLF",
  "GAIL",
  "GODREJCP",
  "HAVELLS",
  "ICICIPRULI",
  "IGL",
  "INDIGO",
  "IOC",
  "JINDALSTEL",
  "LUPIN",
  "MARICO",
  "MCDOWELL-N",
  "MPHASIS",
  "MRF",
  "NAUKRI",
  "NMDC",
  "PAGEIND",
  "PERSISTENT",
  "PETRONET",
  "PIDILITIND",
  "POLYCAB",
  "SAIL",
  "SIEMENS",
  "SRF",
  "TORNTPHARM",
  "TRENT",
  "UPL",
  "VEDL",
  "VOLTAS",
  "ZYDUSLIFE",
] as const

export type NseSymbol = (typeof NSE_SYMBOLS)[number]
